name: Send Email Reminder
on: 
  schedule:
    - cron: '05 17 * * *'

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.20'
      - name: Send Email
        run: go run main.go

